### ISSUE TITLE
Erreur lors de l'exécution de mon JAR velos dans le cours "Déployer Storm en production"

### ISSUE THREAD

**Issue by theirman** [oc-courses/gerez-des-flux-de-donnees-temps-reel#1]
Bonjour,
Je rencontre l'erreur ci-dessous lorsque je lance `storm jar target/velos-1.0-SNAPSHOT.jar velos.App remote`. Que puis-je faire ? 

```
Running: /usr/lib/jvm/java/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/apps/storm -Dstorm.log.dir=/apps/storm/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib:/usr/lib64 -Dstorm.conf.file= -cp /apps/storm/*:/apps/storm/lib/*:/apps/storm/extlib/*:target/velos-1.0-SNAPSHOT.jar:/apps/storm/conf:/apps/storm/bin: -Dstorm.jar=target/velos-1.0-SNAPSHOT.jar -Dstorm.dependency.jars= -Dstorm.dependency.artifacts={} velos.App remote
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/storm/kafka/spout/KafkaSpoutConfig
	at velos.App.main(App.java:22)
Caused by: java.lang.ClassNotFoundException: org.apache.storm.kafka.spout.KafkaSpoutConfig
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```
App.java
```
package velos;

import org.apache.storm.Config;
import org.apache.storm.LocalCluster;
import org.apache.storm.StormSubmitter;
import org.apache.storm.generated.AlreadyAliveException;
import org.apache.storm.generated.AuthorizationException;
import org.apache.storm.generated.InvalidTopologyException;
import org.apache.storm.generated.StormTopology;
import org.apache.storm.kafka.spout.KafkaSpout;
import org.apache.storm.kafka.spout.KafkaSpoutConfig;
import org.apache.storm.topology.TopologyBuilder;
import org.apache.storm.topology.base.BaseWindowedBolt;
import org.apache.storm.tuple.Fields;

public class App 
{
    public static void main( String[] args ) throws AlreadyAliveException, InvalidTopologyException, AuthorizationException 
    {
        TopologyBuilder builder = new TopologyBuilder();

        KafkaSpoutConfig.Builder<String, String> spoutConfigBuilder = KafkaSpoutConfig.builder("localhost:9092", "velib-stations");
        spoutConfigBuilder.setGroupId("city-stats");
        KafkaSpoutConfig<String, String> spoutConfig = spoutConfigBuilder.build();

        builder.setSpout("stations", new KafkaSpout<String, String>(spoutConfig));

        builder.setBolt("station-parsing", new StationParsingBolt()).shuffleGrouping("stations");
        builder.setBolt("city-stats", new CityStatsBolt().withTumblingWindow(BaseWindowedBolt.Duration.of(1000*60*5))).fieldsGrouping("station-parsing", new Fields("city"));
        builder.setBolt("save-results",  new SaveResultsBolt()).fieldsGrouping("city-stats", new Fields("city"));

        StormTopology topology = builder.createTopology();

        Config config = new Config();
        config.setMessageTimeoutSecs(60*30);
        String topologyName = "velos";
        if(args.length > 0 && args[0].equals("remote")) {
            StormSubmitter.submitTopology(topologyName, config, topology);
        }
        else 
        {
            LocalCluster cluster = new LocalCluster();
            cluster.submitTopology(topologyName, config, topology);
        }
    }
}
```
pom.xml

> <?xml version="1.0" encoding="UTF-8"?>
> 
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>   <modelVersion>4.0.0</modelVersion>
> 
>   <groupId>velos</groupId>
>   <artifactId>velos</artifactId>
>   <version>1.0-SNAPSHOT</version>
> 
>   <name>velos</name>
>   
>   <url>http://www.example.com</url>
> 
>   <properties>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     <maven.compiler.source>1.7</maven.compiler.source>
>     <maven.compiler.target>1.7</maven.compiler.target>
>   </properties>
> 
>   <dependencies>
>     <dependency>
>       <groupId>junit</groupId>
>       <artifactId>junit</artifactId>
>       <version>4.11</version>
>       <scope>test</scope>
>       </dependency>
>       <dependency>
>       <groupId>org.apache.storm</groupId>
>       <artifactId>storm-core</artifactId>
>       <version>2.1.0</version>
>       <scope>provided</scope>
>     </dependency>
>     <dependency>
>       <groupId>org.apache.kafka</groupId>
>       <artifactId>kafka_2.12</artifactId>
>       <version>2.3.1</version>
>       <exclusions>
>         <exclusion>
>           <groupId>org.apache.zookeeper</groupId>
>           <artifactId>zookeeper</artifactId>
>         </exclusion>
>         <exclusion>
>           <groupId>log4j</groupId>
>           <artifactId>log4j</artifactId>
>         </exclusion>
>       </exclusions>
>     </dependency>
>     <dependency>
>       <groupId>org.apache.storm</groupId>
>       <artifactId>storm-kafka-client</artifactId>
>       <version>2.1.0</version>
>       <scope>provided</scope>
>     </dependency>
>   </dependencies>
> 
>   <build>
>     <pluginManagement>
>       <plugins>
>         
>         <plugin>
>           <artifactId>maven-clean-plugin</artifactId>
>           <version>3.1.0</version>
>         </plugin>
>         
>         <plugin>
>           <artifactId>maven-resources-plugin</artifactId>
>           <version>3.0.2</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-compiler-plugin</artifactId>
>           <version>3.8.0</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-surefire-plugin</artifactId>
>           <version>2.22.1</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-jar-plugin</artifactId>
>           <version>3.0.2</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-install-plugin</artifactId>
>           <version>2.5.2</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-deploy-plugin</artifactId>
>           <version>2.8.2</version>
>         </plugin>
>         
>         <plugin>
>           <artifactId>maven-site-plugin</artifactId>
>           <version>3.7.1</version>
>         </plugin>
>         <plugin>
>           <artifactId>maven-project-info-reports-plugin</artifactId>
>           <version>3.0.0</version>
>         </plugin>
>       </plugins>
>     </pluginManagement>
>   </build>
> </project>
>

**Comment by regisb** [comment]
Malheureusement je ne suis pas en position de fournir du support à tous les étudiants de ce cours. Merci de poser votre question à votre mentor ou dans les forums d'Openclassrooms.
